apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wear-watch
  annotations: 
    kubernetes.io/ingress.class: "nginx" # Specifying NGINX Ingress controller
spec:
  rules: # routing rules
  - http: # HTTP routing
      paths:
      - path: /wear
        pathType: Prefix
        backend:
          service:
            name: wear-service
            port:
              number: 80
      - path: /watch
        pathType: Prefix
        backend:
          service:
            name: watch-service
            port:
              number: 80