apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watch
  template:
    metadata:
      labels:
        app: watch
    spec:
      containers:
      - name: watch
        image: nginx:alpine
        ports:
        - containerPort: 80